---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '^docs/.*$'
      - id: trailing-whitespace
        exclude: '^docs/.*$'
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt --
        language: system
        files: '\.rs$'
        args: []
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        files: '\.rs$'
        pass_filenames: false
      - id: mdbook
        name: mdbook
        files: 'doc/book.md'
        pass_filenames: false
        entry: 'mdbook'
        args: ['build', 'doc']
        language: 'system'
